### ISSUE TITLE
Bad return status for module build on kernel: 6.5.0-44-generic (x86_64)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linux-thinkpad/tp_smapi#66]
```
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.5.0-44-generic

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=6.5.0-44-generic -C /lib/modules/6.5.0-44-generic/build M=/var/lib/dkms/tp_smapi/0.43/build HDAPS=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.0-44-generic (x86_64)
```
Here is the makelog.

> DKMS make.log for tp_smapi-0.43 for kernel 6.5.0-44-generic (x86_64)
> Thu 18 Jul 01:06:08 BST 2024
> make: Entering directory '/usr/src/linux-headers-6.5.0-44-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   CC [M]  /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.o
>   CC [M]  /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.o
>   CC [M]  /var/lib/dkms/tp_smapi/0.43/build/hdaps.o
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:94:42: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
>    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
>       |                                          ^
> In file included from /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:45:
> ./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
>    34 | #define DEFINE_SEMAPHORE(_name, _n)     \
>       | 
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:94:8: error: type defaults to ‘int’ in declaration of ‘DEFINE_SEMAPHORE’ [-Werror=implicit-int]
>    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
>       |        ^~~~~~~~~~~~~~~~
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c: In function ‘thinkpad_ec_lock’:
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:112:35: error: ‘thinkpad_ec_mutex’ undeclared (first use in this function); did you mean ‘thinkpad_ec_lock’?
>   112 |         ret = down_interruptible(&thinkpad_ec_mutex);
>       |                                   ^~~~~~~~~~~~~~~~~
>       |                                   thinkpad_ec_lock
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:112:35: note: each undeclared identifier is reported only once for each function it appears in
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c: In function ‘thinkpad_ec_try_lock’:
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:126:30: error: ‘thinkpad_ec_mutex’ undeclared (first use in this function); did you mean ‘thinkpad_ec_lock’?
>   126 |         return down_trylock(&thinkpad_ec_mutex);
>       |                              ^~~~~~~~~~~~~~~~~
>       |                              thinkpad_ec_lock
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c: In function ‘thinkpad_ec_unlock’:
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:138:13: error: ‘thinkpad_ec_mutex’ undeclared (first use in this function); did you mean ‘thinkpad_ec_lock’?
>   138 |         up(&thinkpad_ec_mutex);
>       |             ^~~~~~~~~~~~~~~~~
>       |             thinkpad_ec_lock
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c: In function ‘thinkpad_ec_try_lock’:
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:127:1: error: control reaches end of non-void function [-Werror=return-type]
>   127 | }
>       | ^
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c: At top level:
> /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.c:94:8: warning: ‘DEFINE_SEMAPHORE’ defined but not used [-Wunused-variable]
>    94 | static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
>       |        ^~~~~~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/tp_smapi/0.43/build/thinkpad_ec.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:115:36: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
>   115 | static DEFINE_SEMAPHORE(smapi_mutex);
>       |                                    ^
> In file included from ./include/linux/fs.h:25,
>                  from ./include/linux/proc_fs.h:10,
>                  from /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:41:
> ./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
>    34 | #define DEFINE_SEMAPHORE(_name, _n)     \
>       | 
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:115:8: error: type defaults to ‘int’ in declaration of ‘DEFINE_SEMAPHORE’ [-Werror=implicit-int]
>   115 | static DEFINE_SEMAPHORE(smapi_mutex);
>       |        ^~~~~~~~~~~~~~~~
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c: In function ‘store_battery_start_charge_thresh’:
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:780:15: error: ‘smapi_mutex’ undeclared (first use in this function)
>   780 |         down(&smapi_mutex);
>       |               ^~~~~~~~~~~
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:780:15: note: each undeclared identifier is reported only once for each function it appears in
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c: In function ‘store_battery_stop_charge_thresh’:
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:822:15: error: ‘smapi_mutex’ undeclared (first use in this function)
>   822 |         down(&smapi_mutex);
>       |               ^~~~~~~~~~~
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c: At top level:
> /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.c:115:8: warning: ‘DEFINE_SEMAPHORE’ defined but not used [-Wunused-variable]
>   115 | static DEFINE_SEMAPHORE(smapi_mutex);
>       |        ^~~~~~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/tp_smapi/0.43/build/tp_smapi.o] Error 1
> make[1]: *** [/usr/src/linux-headers-6.5.0-44-generic/Makefile:2039: /var/lib/dkms/tp_smapi/0.43/build] Error 2
> make: *** [Makefile:234: __sub-make] Error 2
> make: Leaving directory '/usr/src/linux-headers-6.5.0-44-generic'

**My system**

X230
Linux Mint 21.3 (based on Ubuntu 22.04)
tp_smapi-0.43
TLP 1.6.1

**Comment by LinuxOnTheDesktop** [comment]
Ah: perhaps I need tp_smapi-0.44. (Cf. #49.) I could try compiling that from source. Or I could wait for Mint 22, which is in beta.

**Comment by evgeni** [comment]
Yeah, that's fixed in .44

You can probably install that one package from Mint 22?

**Comment by evgeni** [comment]
But then again, tp smapi shouldn't work on an X230, it's too new

**Comment by LinuxOnTheDesktop** [comment]
evegeni: thanks. How can I tell whether tp smapi is working? The machine does seem to have battery thresholds that have been set successfully by tlp.

**Comment by evgeni** [comment]
Does the module load (look in `lsmod`)?
I'd expect tlp to use the native acpi methods on such modern hardware.

**Comment by LinuxOnTheDesktop** [comment]
Thank you.

I find the following is the case with my X230 (which is running a 6.5 kernel).

1) The machine is implementing battery thresholds set in tlp.
2) The machine does not have the 'smapi' module installed.
3) The machine does have a package installed called 'tp-smapi-dkms' installed.
4) The output of `sudo tlp-stat -b' has no section labelled 'recommendations', even though the documentation that mentions the recommendations section is for the very version of tlp that I have installed, viz., TLP 1.6.1.

I take it from 1-3 that I should uninstall tp-smapi-dkms. 4 remains a puzzle to me.

Thank you for your time.

**Comment by evgeni** [comment]
Yeah, if the module isn't loaded, you can drop that dkms package.

Do you have acpi-call-dkms installed?

**Comment by LinuxOnTheDesktop** [comment]
I do!

**Comment by evgeni** [comment]
I guess that's what's used for thresholds then.
(I recall there is even native support in the kernel, but not sure if it supports all models)
